---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-php-config
data:
  uploads.ini: |-
    file_uploads = On
    upload_max_filesize = 64M
    post_max_size = 64M
    memory_limit = 32M
    max_execution_time = 300
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-php-config
data:
  redis.ini: |-
    extension = redis.so
    session.save_handler = redis
    session.save_path = tcp://redis-service.default.svc.cluster.local:6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
#          image: wordpress:6.6.2-php8.1-apache
          image: olsarnow/wordpress
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
            - mountPath: /usr/local/etc/php/conf.d/uploads.ini
              name: php-config
              subPath: uploads.ini
            - mountPath: /usr/local/etc/php/conf.d/redis.ini
              name: redis-config
              subPath: redis.ini
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-service.default.svc.cluster.local
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_NAME
              value: mysql
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wordpress-pvc
        - configMap:
            defaultMode: 420
            name: wp-php-config
          name: php-config
        - configMap:
            defaultMode: 420
            name: redis-php-config
          name: redis-config
---
kind: Service
apiVersion: v1
metadata:
  name: wordpress-service
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
