replicaCount: 1
namespace: gob
domainname: go-bornholm.de

image:
  repository: wordpress
  tag: "php8.4-apache"

service:
  port: 80
  targetPort: 80
  type: ClusterIP
pvc:
  mode: ReadWriteOnce
  size: 10G

config:
  mysqlhost: mysql-service.gob.svc.cluster.local
  mysqlpass: lxeh9823ryf3h
  mysqluser: root
  mysqldb: mysql
