replicaCount: 1
namespace: wordpress
domainname: go-bornholm.de

image:
  repository: olsarnow/wordpress
  tag: "latest"

service:
  port: 80
  targetPort: 80
  type: ClusterIP
pvc:
  mode: ReadWriteOnce
  size: 10G

config:
  mysqlhost: mysql-service.wordpress.svc.cluster.local
  mysqlpass: lxeh9823ryf3h
  mysqluser: root
  mysqldb: mysql
  redishost: redis-service.wordpress.svc.cluster.local
  redisport: 6379
  memcachedhost: memcached-service.wordpress.svc.cluster.local
  memcachedport: 11211
