apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-wordpress
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: obrehmer@gmail.com
    privateKeySecretRef:
      name: letsencrypt-wordpress
    solvers:
      - http01:
          ingress:
            class: wordpress
