---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-php-config
  namespace: {{ .Values.namespace }}
data:
  uploads.ini: |-
    file_uploads = On
    upload_max_filesize = 64M
    post_max_size = 64M
    memory_limit = 32M
    max_execution_time = 300
