---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-php-config
  namespace: {{ .Values.namespace }}
data:
  uploads.ini: |-
    file_uploads = On
    upload_max_filesize = 64M
    post_max_size = 64M
    memory_limit = 32M
    max_execution_time = 300
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-php-config
  namespace: {{ .Values.namespace }}
data:
  redis.ini: |-
    extension = redis.so
    session.save_handler = redis
    session.save_path = tcp://{{ .Values.config.redishost }}:{{ .Values.config.redisport }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: memcached-config
  namespace: {{ .Values.namespace }}
data:
  memcached.conf: |-
    LoadModule cache_module /usr/lib/apache2/modules/mod_cache.so
    LoadModule cache_socache_module /usr/lib/apache2/modules/mod_cache_socache.so
    LoadModule socache_memcache_module /usr/lib/apache2/modules/mod_socache_memcache.so
    CacheSocache memcache:{{ .Values.config.memcachedhost }}:{{ .Values.config.memcachedport }}

    ###
