---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm
  namespace: {{ .Values.namespace }}
  labels:
    app: php-fpm
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 9000
