---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: {{ .Values.namespace }}
  labels:
    app: apache
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/apache2/conf-enabled/php-fpm.conf
              name: apache-fpm-config
              subPath: php-fpm.conf
      volumes:
        - configMap:
            name: apache-fpm-config
            defaultMode: 420
          name: apache-fpm-config
